### ISSUE TITLE
[JENKINS-43123] Publish over SSH: sudo does not work

### ISSUE THREAD

**Issue by jira-importer** [jenkinsci/publish-over-ssh-plugin#123]
<p>When I try to start a service from jenkins job it gives the following error, however the same works without an issue from Putty.<br/>
SSH: Connecting from host <span class="error">&#91;ABC&#93;</span><br/>
SSH: Connecting with configuration <span class="error">&#91;DEF&#93;</span> ...<br/>
SSH: Creating session: username <span class="error">&#91;abc_123&#93;</span>, hostname <span class="error">&#91;1.1.1.1&#93;</span>, port <span class="error">&#91;22&#93;</span><br/>
SSH: Connecting session ...<br/>
SSH: Connected<br/>
SSH: Opening exec channel ...<br/>
SSH: EXEC: channel open<br/>
SSH: EXEC: STDOUT/STDERR from command [echo <span class="error">&#91;*******&#93;</span> | sudo -S service hybris stop] ...<br/>
SSH: EXEC: connected<br/>
<span class="error">&#91;sudo&#93;</span> password for abc_123: sudo: service: command not found<br/>
SSH: EXEC: completed after 200 ms<br/>
SSH: Disconnecting configuration <span class="error">&#91;DEF&#93;</span> ...<br/>
ERROR: Exception when publishing, exception message [Exec exit status not zero. Status <span class="error">&#91;1&#93;</span>]<br/>
Build step 'Send files or execute commands over SSH' changed build result to UNSTABLE<br/>
Finished: UNSTABLE</p>

---
<details><summary><i>Originally reported by <a title="Revathi Manikoth" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=revathi_manikoth">revathi_manikoth</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-43123" target="_blank">Publish over SSH: sudo does not work</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Alex Earl" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=slide_o_mix">slide_o_mix</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Incomplete
<li><b>resolved</b>: 2018-04-14T20:20:17+10:00
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by h1manshu98** [comment]
Please check you Exec Command field.
I had the same error because in 'Exec Command' field, I mistakenly put ^ mark instead of * mark [ ^.html  instead of *.html ]
