### ISSUE TITLE
[JENKINS-36553] Allow scp -p to preserve executable bits

### ISSUE THREAD

**Issue by jira-importer** [jenkinsci/publish-over-ssh-plugin#135]
<p>Currently, the publish over SSH mechanism executes a scp command.</p>

<p>If some files have the executable bits, and are invoked where deployed as executable, we lost this information.</p>

<p>We should preserve it using scp -p, either by default, either to avoid to break compatibility through an option.</p>

---
<details><summary><i>Originally reported by <a title="Sébastien Santoro" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=dereckson">dereckson</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-36553" target="_blank">Allow scp -p to preserve executable bits</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by gmcdonald** [comment]
This has been fixed and merged in #34
