### ISSUE TITLE
Can't use Chinese as server name

### ISSUE THREAD

**Issue by liuweiGL** [jenkinsci/publish-over-ssh-plugin#240]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.332.1
OS: Linux - 5.4.0-58-generic
---
publish-over:0.22
publish-over-ssh:1.24
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows 10

### Reproduction steps

Configure the SSH Servers

### Expected Results

Showing original Chinese name:

![image](https://user-images.githubusercontent.com/21048878/159208389-f2d7e052-f1d2-4680-ace5-0efaf8badfd2.png)

### Actual Results

Chinese is escaped to Unicode:

![image](https://user-images.githubusercontent.com/21048878/159208350-d3e32b8f-f9ae-40b8-a0c3-58034ce48854.png)

### Anything else?

Why this is necessary:

https://github.com/jenkinsci/publish-over-ssh-plugin/commit/cdfeea74f3c01980856ac46ef28bdbc3fdda132d

**Comment by yangweijie** [comment]
same

**Comment by Jmingzi** [comment]
看 [pr 文件](https://github.com/jenkinsci/publish-over-ssh-plugin/pull/59/files)修改，取名字的时候应该 unescape 才对。
降级到 1.23 吧。

**Comment by gmcdonald** [comment]
@liuweiGL - Are you saying this is a regression introduced in  https://github.com/jenkinsci/publish-over-ssh-plugin/commit/cdfeea74f3c01980856ac46ef28bdbc3fdda132d ?

**Comment by liuweiGL** [comment]
yes

**Comment by derline** [comment]
same. This is a bug for Chinese characters.

**Comment by gmcdonald** [comment]
@olamy can you look into this, apparantly your removal of some loc at https://github.com/jenkinsci/publish-over-ssh-plugin/pull/61/files has caused this.

**Comment by derline** [comment]
@olamy Please!

**Comment by liunancun** [comment]
Can this fix be compiled separately for a version of jdk8?

**Comment by derline** [comment]
> @liuweiGL hi, Can this fix be compiled separately for a version of jdk8? Jenkins version 2.346.3 cannot install version 1.25 of this.

准备找 jenkins 替代品吧，它太老了。

**Comment by derline** [comment]
我已经放弃这家伙了

**Comment by olamy** [comment]
> @liuweiGL hi, Can this fix be compiled separately for a version of jdk8? Jenkins version 2.346.3 cannot install version 1.25 of this.

@liunancun  2.346.3 is old now and suffers from few security issues. Maybe you should have a look at upgrading your Jenkins version? The minimum required now is 2.361.4
Does something prevent you from upgrading?
