### ISSUE TITLE
public over ssh is not there in plugins

### ISSUE THREAD

**Issue by Manojgoud11111** [jenkinsci/publish-over-ssh-plugin#249]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

linux

### Reproduction steps

i installed plugin and i uninstalled 

### Expected Results

problem solving

### Actual Results

when i tried to install plugin there is no publish over ssh plugin icant download it y

### Anything else?

no

**Comment by gmcdonald** [comment]
Can I ask which Jenkins version you are using?

Also, you say you 'installed' and then 'uninstalled' "

1. why did you have to uninstall?
2. Which version of the publish over ssh plugin did you install and then uninstall?

Thanks for your responses

**Comment by gmcdonald** [comment]
Can not reproduce
