### ISSUE TITLE
[JENKINS-67963] Add option to save bandwidth and resources, which are wasted unnecessarily

### ISSUE THREAD

**Issue by jira-importer** [jenkinsci/publish-over-ssh-plugin#65]
<p>At this moment, the plugin always sends full build artifacts (tons of media files and etc) over each build, which is an absolute overkill and waste of:</p>
<ul>
	<li>resources & performance of Jenkins environment</li>
	<li>resources & performance of staging/production site </li>
</ul>

<p>so, whenever you have a chance, please implement this trivial things - before sending the artifact files, compare them to last sent file's md5 (or whatever) signature, and if content is not changed, don't resend. You can leave that 'option' by default turned off, but at least, give us way to enable that option.</p>

---
<details><summary><i>Originally reported by <a title="s m" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=selnomeria">selnomeria</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-67963" target="_blank">Add option to save bandwidth and resources, which are wasted unnecessarily</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by ttodua** [comment]
i dont think this is specifically part of this plugin. this plugin just adds window of 'send files through ssh' functionality of core Jenkins. So, that functionality exists inside Jenkins core, and not in this plugin as I think. however, I might be wrong. 
I agree, that is very needed feature.

**Comment by ttodua** [comment]
There is also bounty for this functionality:  https://app.bountysource.com/issues/106189146-jenkins-67963-add-option-to-save-bandwidth-and-resources-which-are-wasted-unnecessarily

**Comment by parvit** [comment]
Hi @ttodua, i've come across the bounty and i've worked on this the last couple of days.
Please see my change at https://github.com/parvit/publish-over-ssh-plugin/tree/JENKINS-67963 and tell me if there is anything else necessary.

Regards.

**Comment by ttodua** [comment]
@parvit Hey parvit, nice to see you worked on it. I'll review and let you know within 24 hours, thanks

**Comment by ttodua** [comment]
@parvit just a question - if you wish, I can release the bounty now onto you, but if I will find a relatively simple bug/issue later, will you be able to address that? of course, I dont mean adding other things, just that what you worked on.

**Comment by ttodua** [comment]
also if you can, make a PR to this main repository, so author can merge too.

**Comment by ttodua** [comment]
@parvit it shows me (first time I've used it) that the issue needs to be closed in order to request bounty. So, if I am right, @gmcdonald should be able to merge & close the issue. 

@gmcdonald can you confirm?

**Comment by parvit** [comment]
@ttodua Hi, is there any update? thanks.

**Comment by gmcdonald** [comment]
Thanks @parvit and @ttodua - I dont want to hold this up, but I do want to test everything before merging.
I'll try and get this done tomorrow

**Comment by ttodua** [comment]
> Thanks @parvit and @ttodua - I dont want to hold this up, but I do want to test everything before merging. I'll try and get this done tomorrow

@gmcdonald thanks! sure, don't hurry, just wanted to get any reply from you, to know that you are notified about this. thanks again !

**Comment by parvit** [comment]
@ttodua @gmcdonald Hi, is there anything i can help with to speed up the test? If you're busy i can do it for you and post a report.

**Comment by gmcdonald** [comment]
I downloaded the PR into a new branch and tested. It all seems to work fine. @parvit it would not hurt if you also want to provide some test results as confirmation and then I will merge.

One thing to note - the new feature checkbox is only available from the Admin - > Configure area of Jenkins and so it not configurable at job/user level. The original issue did not make it clear whether or not this is needed. In my opinion it is a 'nice to have' - perhaps extend to be able to override the Admin setting at job level, I will leave that to others to open a new Issue if they think it beneficial.

I am happy to merge, but if @parvit is able to provide a test also then I'd prefer that 2nd opinion.

**Comment by parvit** [comment]
sure, later i'll provide logs of the tests.

**Comment by parvit** [comment]
I've updated the PR with the test logs.

**Comment by gmcdonald** [comment]
PR merged, thank you.

**Comment by ttodua** [comment]
@parvit please click "claim the bounty" : https://app.bountysource.com/issues/106189146-jenkins-67963-add-option-to-save-bandwidth-and-resources-which-are-wasted-unnecessarily

**Comment by parvit** [comment]
@ttodua @gmcdonald Thank you.
